requirements:
- name: Service introspection cpp
  shortname: service_introspectio
  description: ''
  steps:
  - name: Run the client and server
    description: null
    action:
    - !StdIn
      number: 1
      text: ros2 launch demo_nodes_cpp introspect_services_launch.py
    - !StdIn
      number: 2
      text: ros2 topic list --include-hidden-topics
    expect:
    - !StdOut
      number: 1
      text: |
        [introspection_service-1] a: 2 b: 3
        [introspection_client-2] [INFO] [1680585324.964598437] [introspection_client]: Result of add_two_ints: 5
    - !StdOut
      number: 2
      text: |
        /parameter_events
        /rosout
  - name: Configure service to send introspection metadata
    description: null
    action:
    - !StdIn
      number: 1
      text: ros2 launch demo_nodes_cpp introspect_services_launch.py
    - !StdIn
      number: 2
      text: ros2 param set /introspection_service service_configure_introspection metadata
    - !StdIn
      number: 2
      text: ros2 topic echo /add_two_ints/_service_event
    expect:
    - !StdOut
      number: 1
      text: |
        [introspection_service-1] a: 2 b: 3
        [introspection_client-2] [INFO] [1680585324.964598437] [introspection_client]: Result of add_two_ints: 5
    - !StdOut
      number: 2
      text: |
        info:
          event_type: 1
          stamp:
            sec: 1680586531
            nanosec: 726539263
          client_gid:
          - 83
          - 143
          - 248
          - 38
          - 47
          - 231
          - 185
          - 230
          - 98
          - 17
          - 45
          - 187
          - 128
          - 124
          - 253
          - 156
          sequence_number: 46
        request: []
        response: []
        ---
        info:
          event_type: 2
          stamp:
            sec: 1680586531
            nanosec: 726695003
          client_gid:
          - 83
          - 143
          - 248
          - 38
          - 47
          - 231
          - 185
          - 230
          - 98
          - 17
          - 45
          - 187
          - 128
          - 124
          - 253
          - 156
          sequence_number: 46
        request: []
        response: []
  - name: Configure client to send introspection metadata
    description: null
    action:
    - !StdIn
      number: 1
      text: ros2 launch demo_nodes_cpp introspect_services_launch.py
    - !StdIn
      number: 2
      text: ros2 param set /introspection_client client_configure_introspection metadata
    - !StdIn
      number: 2
      text: ros2 topic echo /add_two_ints/_service_event
    expect:
    - !StdOut
      number: 1
      text: |
        [introspection_service-1] a: 2 b: 3
        [introspection_client-2] [INFO] [1680585324.964598437] [introspection_client]: Result of add_two_ints: 5
    - !StdOut
      number: 2
      text: |
        info:
          event_type: 0
          stamp:
            sec: 1680586637
            nanosec: 158736272
          client_gid:
          - 1
          - 16
          - 34
          - 142
          - 114
          - 128
          - 207
          - 116
          - 98
          - 246
          - 204
          - 52
          - 0
          - 0
          - 0
          - 7
          sequence_number: 48
        request: []
        response: []
        ---
        info:
          event_type: 3
          stamp:
            sec: 1680586637
            nanosec: 159157853
          client_gid:
          - 1
          - 16
          - 34
          - 142
          - 114
          - 128
          - 207
          - 116
          - 98
          - 246
          - 204
          - 52
          - 0
          - 0
          - 0
          - 7
          sequence_number: 48
        request: []
        response: []
  labels:
  - executable
  - feature
  links:
  - name: demo_nodes_cpp
    url: https://github.com/ros2/demos/tree/kilted/demo_nodes_cpp
