requirements:
  - name: Topic executables in `demo_nodes_py`
    labels:
      - executable
      - feature
      - demos-py
    checks:
      - name: Check `listener` and `talker`
        try:
          - stdin: ros2 run demo_nodes_py talker
            terminal: 1
          - stdin: ros2 run demo_nodes_py listener
            terminal: 2
      - name: Check `listener` and `talker` QOS
        try:
          - stdin: ros2 run demo_nodes_py talker_qos
            terminal: 1
          - stdin: ros2 run demo_nodes_py listener_qos
            terminal: 2
      - name: Check serialized `listener` and `talker`
        try:
          - stdin: ros2 run demo_nodes_py talker
            terminal: 1
          - stdin: ros2 run demo_nodes_py listener_serialized
            terminal: 2
  - name: Service executables in `demo_nodes_py`
    labels:
      - executable
      - feature
      - demos-py
    checks:
      - name: Add two ints
        try:
          - stdin: ros2 run demo_nodes_py add_two_ints_client
            terminal: 1
          - stdin: ros2 run demo_nodes_py add_two_ints_server
            terminal: 2
      - name: Add two ints async
        try:
          - stdin: ros2 run demo_nodes_py add_two_ints_client_async
            terminal: 1
          - stdin: ros2 run demo_nodes_py add_two_ints_server
            terminal: 2
  - name: Parameter executables in `demo_nodes_py`
    labels:
      - executable
      - feature
      - demos-py
    checks:
      - name: Async parameter client
        try:
          - stdin: ros2 run demo_nodes_cpp parameter_blackboard
            terminal: 1
          - stdin: ros2 run demo_nodes_py async_param_client
            terminal: 2
  - name: Check Lifecyle node py
    labels:
      - executable
      - feature
      - demos-py
    links:
      - name: Lifecycle Py
        url: https://github.com/ros2/demos/tree/iron/lifecycle_py
    checks:
      - name: Check `listener` and `talker`
        try:
          - stdin: ros2 run lifecycle_py lifecycle_talker
            terminal: 1
          - stdin: ros2 lifecycle nodes
            terminal: 2
          - stdin: ros2 lifecycle set /lc_talker 1
            terminal: 2
          - stdin: ros2 lifecycle set /lc_talker 3
            terminal: 2
        expect:
          - stdout: |
              [INFO] [1680583079.479073069] [lc_talker]: on_configure() is called.
              [INFO] [1680583080.439717509] [lc_talker]: Lifecycle publisher is inactive. Messages are not published.
            terminal: 1
          - stdout: /lc_talker
            terminal: 2
          - stdout: Transitioning successful
            terminal: 2
          - stdout: |
              [INFO] [1680583403.113550155] [lc_talker]: on_activate() is called.
              [INFO] [1680583403.439875193] [lc_talker]: Lifecycle publisher is active. Publishing: [Lifecycle HelloWorld #323]
            terminal: 2
