name: YATM Sync Issues

on:
  push:
    branches: [ main, lyrical_prep ]

env:
  CONFIG_PATH: config/lyrical/test-case.config.yaml

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout ros2_test_cases
        uses: actions/checkout@v4

      - name: Checkout yatm-v2
        uses: actions/checkout@v4
        with:
          repository: paudrow/yatm-v2
          ref: main
          path: yatm-v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workdir: yatm-v2
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            yatm-v2/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('yatm-v2/**/Cargo.lock') }}
      - name: Build yatm-v2
        run: cargo build --release
        working-directory: yatm-v2

      - name: Substitute repo info
        run: |
          sed -i "s/repo_owner: .*/repo_owner: ${{ github.repository_owner }}/" ${{ env.CONFIG_PATH }}
          sed -i "s/repo_name: .*/repo_name: ${{ github.event.repository.name }}/" ${{ env.CONFIG_PATH }}

      - name: Sync YATM Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./yatm-v2/target/release/yatm_v2 github upload -c ${{ env.CONFIG_PATH }} -n
