name: YATM Validate

on:
  push:
    # branches: [ main, master ]
  pull_request:
    # branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ros2_test_cases
        uses: actions/checkout@v4

      - name: Checkout yatm-v2
        uses: actions/checkout@v4
        with:
          repository: paudrow/yatm-v2
          ref: main
          path: yatm-v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workdir: yatm-v2
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            yatm-v2/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('yatm-v2/**/Cargo.lock') }}
      - name: Build yatm-v2
        run: cargo build --release
        working-directory: yatm-v2

      - name: Validate YATM Config
        run: |
          ../../yatm-v2/target/release/yatm_v2 github validate -c test-case.config.yaml
        working-directory: config/lyrical
